import { test } from "node:test";
import assert from "node:assert/strict";
import { structuredDiff, normalizePath } from "../src/core/diff.ts";

// Reference answers below are hand-written expectations, NOT generated by
// the diff engine itself.

test("nested object field-level diff locates exact path", () => {
  const before = { user: { name: "ann", address: { city: "Beijing", zip: "100000" } }, n: 1 };
  const after  = { user: { name: "ann", address: { city: "Shanghai", zip: "100000" } }, n: 1 };
  const diffs = structuredDiff(before, after);
  assert.deepEqual(diffs, [
    { path: "user.address.city", type: "modified", before: "Beijing", after: "Shanghai" },
  ]);
});

test("added and removed object fields are reported with paths and values", () => {
  const before = { a: 1, gone: { x: true } };
  const after  = { a: 1, fresh: "new" };
  const diffs = structuredDiff(before, after);
  assert.deepEqual(diffs, [
    { path: "gone", type: "removed", before: { x: true } },
    { path: "fresh", type: "added", after: "new" },
  ]);
});

test("array element addition and removal are detected by index", () => {
  const before = { items: [1, 2, 3] };
  const after  = { items: [1, 2] };
  assert.deepEqual(structuredDiff(before, after), [
    { path: "items[2]", type: "removed", before: 3 },
  ]);
  assert.deepEqual(structuredDiff(after, before), [
    { path: "items[2]", type: "added", after: 3 },
  ]);
});

test("array element nested modification is located precisely", () => {
  const before = { items: [{ id: 1, v: "a" }, { id: 2, v: "b" }] };
  const after  = { items: [{ id: 1, v: "a" }, { id: 2, v: "B" }] };
  assert.deepEqual(structuredDiff(before, after), [
    { path: "items[1].v", type: "modified", before: "b", after: "B" },
  ]);
});

test("type change of a field is a modification", () => {
  assert.deepEqual(structuredDiff({ x: [1] }, { x: "s" }), [
    { path: "x", type: "modified", before: [1], after: "s" },
  ]);
});

test("identical inputs produce no diffs", () => {
  assert.deepEqual(structuredDiff({ a: [1, { b: null }] }, { a: [1, { b: null }] }), []);
});

test("ignored paths suppress diffs at and below the path", () => {
  const before = { meta: { ts: 1, by: "x" }, data: { v: 1 } };
  const after  = { meta: { ts: 2, by: "x" }, data: { v: 2 } };
  const diffs = structuredDiff(before, after, ["meta.ts"]);
  assert.deepEqual(diffs, [
    { path: "data.v", type: "modified", before: 1, after: 2 },
  ]);
});

test("ignoring a whole subtree suppresses all nested diffs", () => {
  const before = { meta: { ts: 1, by: "x" }, data: 1 };
  const after  = { meta: { ts: 9, by: "y" }, data: 1 };
  assert.deepEqual(structuredDiff(before, after, ["meta"]), []);
});

test("ignore path with array index only affects that element", () => {
  const before = { items: [{ ts: 1 }, { ts: 1 }] };
  const after  = { items: [{ ts: 2 }, { ts: 2 }] };
  const diffs = structuredDiff(before, after, ["items[0].ts"]);
  assert.deepEqual(diffs, [
    { path: "items[1].ts", type: "modified", before: 1, after: 2 },
  ]);
});

test("normalizePath canonicalizes dot-index form", () => {
  assert.equal(normalizePath("items.0.ts"), "items[0].ts");
  assert.equal(normalizePath("a.b[2].c"), "a.b[2].c");
});
