// Graph computation tests. Expected sets/orders below are derived by hand
// from the fixture graph, not generated by the implementation.

import { test } from "node:test";
import { equal, deepEqual, ok } from "node:assert/strict";
import { parseTargets, affectedClosure, topoOrder, downstreamWithin } from "../src/core/graph.ts";
import { ContractError } from "../src/domain/errors.ts";

// lib <- app, lib <- ui, util <- app, docs standalone
const DEFS = {
  targets: [
    { name: "lib", watchPaths: ["src/lib.ts"], dependencies: [] },
    { name: "util", watchPaths: ["src/util.ts"], dependencies: [] },
    { name: "app", watchPaths: ["src/app.ts"], dependencies: ["lib", "util"] },
    { name: "ui", watchPaths: ["src/ui.ts"], dependencies: ["lib"] },
    { name: "docs", watchPaths: ["docs/readme.md"], dependencies: [] },
  ],
};

test("affectedClosure: direct match plus transitive dependents", () => {
  const g = parseTargets(DEFS, 100);
  deepEqual([...affectedClosure(g, ["src/lib.ts"])].sort(), ["app", "lib", "ui"]);
  deepEqual([...affectedClosure(g, ["src/util.ts"])].sort(), ["app", "util"]);
  deepEqual([...affectedClosure(g, ["docs/readme.md"])], ["docs"]);
  deepEqual([...affectedClosure(g, ["src/lib.ts", "src/ui.ts"])].sort(), ["app", "lib", "ui"]);
});

test("affectedClosure: unmatched paths affect nothing", () => {
  const g = parseTargets(DEFS, 100);
  deepEqual([...affectedClosure(g, ["src/unknown.ts"])], []);
});

test("topoOrder: dependencies first, lexicographic tie-break", () => {
  const g = parseTargets(DEFS, 100);
  const affected = affectedClosure(g, ["src/lib.ts"]);
  // hand-derived: lib first; app and ui both ready afterwards, app < ui
  deepEqual(topoOrder(g, affected), ["lib", "app", "ui"]);
  const all = affectedClosure(g, ["src/lib.ts", "src/util.ts", "docs/readme.md"]);
  deepEqual(topoOrder(g, all), ["docs", "lib", "ui", "util", "app"]); // greedy lexicographic Kahn: ui < util once both ready
});

test("downstreamWithin: transitive dependents inside the subset", () => {
  const g = parseTargets(DEFS, 100);
  const affected = affectedClosure(g, ["src/lib.ts"]);
  deepEqual(downstreamWithin(g, "lib", affected).sort(), ["app", "ui"]);
  deepEqual(downstreamWithin(g, "util", affected), ["app"]); // app transitively depends on util
});

test("parseTargets rejects invalid contracts", () => {
  const bad = [
    [{}, "non-object body"],
    [{ targets: [] }, "empty targets"],
    [{ targets: [{ name: "a", watchPaths: ["x"], dependencies: ["ghost"] }] }, "unknown dependency"],
    [{ targets: [
      { name: "a", watchPaths: ["x"], dependencies: ["b"] },
      { name: "b", watchPaths: ["y"], dependencies: ["a"] },
    ] }, "cycle"],
    [{ targets: [
      { name: "a", watchPaths: ["x"], dependencies: [] },
      { name: "a", watchPaths: ["y"], dependencies: [] },
    ] }, "duplicate name"],
    [{ targets: [{ name: "a", watchPaths: "x", dependencies: [] }] }, "watchPaths not array"],
  ];
  for (const [body, label] of bad) {
    let threw = false;
    try {
      parseTargets(body, 100);
    } catch (err) {
      threw = true;
      ok(err instanceof ContractError, label + ": expected ContractError, got " + err);
      equal((err as ContractError).category, "contract");
    }
    ok(threw, label + ": expected parseTargets to throw");
  }
});
