import { test } from "node:test";
import assert from "node:assert/strict";
import { computeStats, percentile } from "../src/stats.ts";
import { AppError } from "../src/errors.ts";

// Reference values below are hand-computed (linear interpolation method),
// not generated by the implementation under test.

test("percentile: boundary values on 10..100 step 10", () => {
  const data = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100];
  // rank = p/100 * (n-1); p50 -> rank 4.5 -> (50+60)/2 = 55
  assert.equal(percentile(data, 50), 55);
  // p90 -> rank 8.1 -> 90 + 0.1*(100-90) = 91
  assert.ok(Math.abs(percentile(data, 90) - 91) < 1e-9);
  // p99 -> rank 8.91 -> 90 + 0.91*10 = 99.1
  assert.ok(Math.abs(percentile(data, 99) - 99.1) < 1e-9);
  assert.equal(percentile(data, 0), 10);
  assert.equal(percentile(data, 100), 100);
});

test("percentile: single and two element samples", () => {
  assert.equal(percentile([42], 50), 42);
  assert.equal(percentile([42], 99), 42);
  assert.equal(percentile([10, 20], 50), 15);
  assert.equal(percentile([10, 20], 90), 19);
});

test("computeStats: full block on known sample", () => {
  const s = computeStats([100, 10, 50, 90, 20, 80, 30, 70, 40, 60]);
  assert.equal(s.count, 10);
  assert.equal(s.minMs, 10);
  assert.equal(s.maxMs, 100);
  assert.equal(s.avgMs, 55);
  assert.equal(s.p50Ms, 55);
  assert.ok(Math.abs(s.p90Ms - 91) < 1e-9);
  assert.ok(Math.abs(s.p99Ms - 99.1) < 1e-9);
});

test("computeStats: empty sample -> CALCULATION_FAILED", () => {
  assert.throws(() => computeStats([]), (e: unknown) => e instanceof AppError && e.code === "CALCULATION_FAILED");
});

test("computeStats: invalid values -> CALCULATION_FAILED", () => {
  assert.throws(() => computeStats([1, Number.NaN]), (e: unknown) => e instanceof AppError && e.code === "CALCULATION_FAILED");
  assert.throws(() => computeStats([-5]), (e: unknown) => e instanceof AppError && e.code === "CALCULATION_FAILED");
});

test("percentile: out-of-range p -> CALCULATION_FAILED", () => {
  assert.throws(() => percentile([1], 101), (e: unknown) => e instanceof AppError && e.code === "CALCULATION_FAILED");
});
