import type { NftEvent } from "../src/contract/types.ts";

// Independent reference implementation of the projection. It is deliberately
// written separately from src/kernel/projection.ts so the rebuild/equality
// assertions are not generated by the code under test.
export interface RefState {
  appliedSeq: number;
  ownership: Record<string, string>;
  volume: number;
  floor: number | null;
  lastSale: Record<string, unknown> | null;
}

export function referenceProjection(events: NftEvent[]): RefState {
  const ownership: Record<string, string> = {};
  let volume = 0;
  let floor: number | null = null;
  let lastSale: Record<string, unknown> | null = null;
  let appliedSeq = 0;

  for (const e of events) {
    if (e.seq !== appliedSeq + 1) {
      throw new Error("reference stream not contiguous at " + e.seq);
    }
    if (e.type === "mint") {
      ownership[e.tokenId] = e.to;
    } else if (e.type === "transfer") {
      if (ownership[e.tokenId] !== e.from) {
        throw new Error("reference invalid transition at " + e.seq);
      }
      ownership[e.tokenId] = e.to;
    } else {
      if (ownership[e.tokenId] !== e.from) {
        throw new Error("reference invalid transition at " + e.seq);
      }
      ownership[e.tokenId] = e.to;
      volume += e.price;
      floor = floor === null ? e.price : Math.min(floor, e.price);
      lastSale = {
        seq: e.seq,
        tokenId: e.tokenId,
        price: e.price,
        from: e.from,
        to: e.to,
      };
    }
    appliedSeq = e.seq;
  }

  return { appliedSeq, ownership, volume, floor, lastSale };
}

export function stateView(s: RefState) {
  return {
    appliedSeq: s.appliedSeq,
    ownership: s.ownership,
    stats: { volume: s.volume, floor: s.floor, lastSale: s.lastSale },
  };
}

